package com.appstats.appstatisticsinfo.utils

object ConstantProperties {
    const val WEEK_DAYS_NUM = 7
    const val MARCH_MONTH_NUM = 3
    const val LEAP_YEAR_PERIOD = 4
    const val DIFFERENCE_DAYS_BETWEEN_GEORGIAN_AND_SOLAR_AT_BEGINNING_OF_SOLAR_YEAR = 79
    const val DIFFERENCE_DAYS_BETWEEN_GEORGIAN_AND_SOLAR_AT_END_OF_SOLAR_YEAR = 286
    const val DAY_NUM_OF_MARCH_MONTH_AT_BEGINNING_OF_SOLAR_LEAP_YEAR = 20
    const val DIFFERENCE_YEARS_BETWEEN_GEORGIAN_AND_SOLAR_AT_BEGINNING_OF_SOLAR_YEAR = 621
    const val DIFFERENCE_YEARS_BETWEEN_GEORGIAN_AND_SOLAR_AT_END_OF_SOLAR_YEAR = 622
}